import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import ConnectButtonComp from './ConnectButton';
export default function Header() {
    
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
                <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500;700&display=swap" rel="stylesheet"/>
            </Head>
            <div className={styles.head}>
                <div className={styles.description}>
                    <p className={styles.headText}>
                        Join our community&nbsp;
                        <code className={styles.code}> Mint Today!</code>
                    </p>
                   <ConnectButtonComp/>  
                </div> 
            </div>
           
        </div>
        
    )
}